# Generated by Django 5.2.10 on 2026-01-12 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique identifier for the IoT device (MAC address or serial number)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Device latitude coordinate",
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Device longitude coordinate",
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current operational status",
                        max_length=20,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last timestamp device communicated with server",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Device registration timestamp"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="iot_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IoT Device",
                "verbose_name_plural": "IoT Devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Captured image file", upload_to="captures/%Y/%m/%d/"
                    ),
                ),
                (
                    "captured",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp when image was captured"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("motion", "Motion Detection"),
                            ("manual", "Manual Capture"),
                            ("live", "Live Stream"),
                        ],
                        help_text="How the image was captured",
                        max_length=20,
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether image has been processed for detections",
                    ),
                ),
                (
                    "animal_detected",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether any animals were detected in the image",
                    ),
                ),
                (
                    "primary_animal",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary animal type detected (most confident)",
                        max_length=50,
                    ),
                ),
                (
                    "max_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Highest confidence score across all detections",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="low",
                        help_text="Highest threat level from detected animals",
                        max_length=20,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created in database",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="IoT device that captured this image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.iotdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-captured"],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique authentication token for the device",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Token creation timestamp"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this token was used for authentication",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this token is active and can be used",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        help_text="IoT device this token belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token",
                        to="api.iotdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Token",
                "verbose_name_plural": "Device Tokens",
            },
        ),
        migrations.CreateModel(
            name="AnimalDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of animal detected",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score (0-1) of the detection",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "bounding_box",
                    models.JSONField(
                        help_text="Bounding box as {x_min, y_min, x_max, y_max} normalized coordinates"
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        help_text="Threat level of this animal type",
                        max_length=20,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Detection timestamp"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image containing this detection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="api.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal Detection",
                "verbose_name_plural": "Animal Detections",
                "ordering": ["-confidence"],
                "indexes": [
                    models.Index(
                        fields=["image", "animal_type"],
                        name="api_animald_image_i_3346d9_idx",
                    ),
                    models.Index(
                        fields=["threat_level"], name="api_animald_threat__2acc10_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("high_threat", "High Threat Animal"),
                            ("repeated_detection", "Repeated Detection"),
                            ("unusual_activity", "Unusual Activity"),
                        ],
                        help_text="Type of alert",
                        max_length=50,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Alert message describing the threat"),
                ),
                (
                    "read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the alert has been read by the user",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Alert creation timestamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving the alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image that triggered the alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["user", "read", "created"],
                        name="api_alert_user_id_e3c53a_idx",
                    ),
                    models.Index(
                        fields=["user", "created"], name="api_alert_user_id_46b078_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(
                fields=["owner", "status"], name="api_iotdevi_owner_i_daf856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(
                fields=["device_id"], name="api_iotdevi_device__9f06d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["device", "captured"], name="api_image_device__4b26db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["processed", "animal_detected"],
                name="api_image_process_ed702a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["threat_level", "created"], name="api_image_threat__e42590_idx"
            ),
        ),
    ]
