# Generated by Django 5.2.10 on 2026-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_avatar_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='animal_type',
            field=models.CharField(choices=[('Bear', 'Bear'), ('Bison', 'Bison'), ('Elephant', 'Elephant'), ('Human', 'Human'), ('Leopard', 'Leopard'), ('Lion', 'Lion'), ('Tiger', 'Tiger'), ('Boar', 'Boar'), ('Bision', 'Bision'), ('Leopord', 'Leopord'), ('Wild Boar', 'Wild Boar')], max_length=20),
        ),
    ]
