# Generated by Django 5.2.10 on 2026-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_capturedimage_animal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="call_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-animal call overrides for this device (bools keyed by animal type)",
            ),
        ),
    ]
