export { default as Login } from './Login';
export { default as Dashboard } from './Dashboard';
export { default as LiveMonitoring } from './LiveMonitoring';
export { default as MapTracking } from './MapTracking';
export { default as DetectionHistory } from './DetectionHistory';
export { default as AlertsCenter } from './AlertsCenter';
export { default as CameraHealth } from './CameraHealth';
export { default as Analytics } from './Analytics';
export { default as Settings } from './Settings';
